module.exports = {

    expireLogSeconds : 259200,
    expireAntiBankingSeconds    : 900,
    expireGameActivityReductantSeconds    : 1296000,
    "comment - expireAntiBankingSeconds" : "when change it, also change rootTools.antiBankingTime in main.js to same value",
    antiBankingBuffer           : 5,
    resetDatabaseOnServerStart  : 10,
    startSchedularOnServerStart : 5,
    startSchedulerServices      : 5,
    playerSpectateLimit         : 600,
    rebuyAboutToEndTime         : 1,
    delayInSitNGoTimer          : 2,
    sitNGoRecurringTimer        : 20,
    delayInNormalTournament     : 2,
    allowSameNetworkPlay        : true,
    rakePercent                 : 4,
    rakeCapValue                : 10,
    capTwo                      : 10,
    capThreeFour                : 20,
    capMoreThanFive             : 40,
    gameOverBroadcastDelay      : 1.5,
    autositoutDelayGameOver     : 0.3,
    deleayInGames               : 6,
    startGameAfterStartEvent    : 0.2,
    recordSummaryAfterGameOver  : 0.8,
    joinBankruptBroadcast       : 0.5,
    autositAndBankruptDelay     : 1,
    playerAutoMoveRequired      : true,
    extraTurnTime               : 10,
    validateGameToPreventLock   : false,
    removeAfterSitoutGameMissed : 2,
    removeAfterDisconnectedGame : 2,
    blindMissed                 : 1,
    ofcRemoveSitoutMissedGame   : 2,
    minPlayersForStraddle       : 3,
    vacantReserveSeatTime       : 10,
    favourateSeatCap            : 10,
    favourateTableCap           : 10,
    lockTableRetryAttempts      : 20,
    lockTableRetryInterval      : 100,
    handTabRecordCount          : 3,
    ofcOverBroadcastDelay       : 2,
    ofcVacantReserveSeatTime    : 20,
    ofcTurnCardBroadcastDelay   : 1,
    deleayInOFCgames            : 4,
    autoLogOutCheckTime         : 300,
    isConnectedCheckTime        : 2,
    logOutTime                  : 18,
    removeObserverRecord        : 5,
    tableIdleTimerSeconds       : 120,
    waitForOutOfMoneySeconds    : 5,
    removeIdleGamePlayers       : true,
    removeIdlePlayersAfter      : 60,
    checkIdlePlayerInterval     : 60,
    considerChipsForTip: false,
    minimumTipAmount : 1,
    percentForBonusRelease : 100,
    isHeadsUpLeaderboard : true,
    gameNameText : "Poker Moogley",
    serverVersion               : "1.0",
    from_email                  : "rishabh@playmoogley.com",
    feedbackMail                : "rishabh@pokermoogley.com",
    mailFromAppName             : "PokerMoogley-Production",
    timebank                    :{
      initialSec : 10,
      earnAfterEveryManyHands : 50,
      earnSec : 10,
      maxSeconds : 30
    }, 
    tableCountAllowed         :{
      browser : 4,
      phone : 2,
      androidApp : 2,
      iosApp : 2,
      windows : 4,
      mac : 4
    },
    mp                          :{
      name: "configs for megaPoints feature",
      countingTime : {"value":1, "unit": "months"},
      expireTime : {"value":6, "unit": "months"}
    },

  serverDown                  :{
      name: "configs for serverDown feature",
      reportTos : ["nishank@playmoogly.com", "rishabh@playmoogly.com"],
      minTimeToServerDownAfterCurrentTime_Minutes: 60,
      disableGameStartBeforeServerDown_Minutes: 55,
      disableLoginBeforeServerDown_Minutes: 10,
      forceLeaveAfterGameDisable_Minutes: 50,
      startKickSessionAfterStartForceLeave_Minutes: 2,
      iterativeForceLeaveAfter_Minutes: 2
  },
  "comment":  "- previously undeclared in systemConfig.json file but used in code",
  ofcLockTableRetryAttempts : undefined,
  ofcLockTableRetryInterval : undefined,
  allowedLockedTime : undefined

}


