var newTables = {};
newTables.newTables=[{
    "isRealMoney" : false,
    "channelName" : "Delhi Richer texas",
    "turnTime" : 20,
    "isPotLimit" : false,
    "maxPlayers" : 9,
    "minPlayers" : 2,
    "smallBlind" : 20,
    "bigBlind" : 40,
    "isStraddleEnable" : false,
    "minBuyIn" : 500,
    "maxBuyIn" : 2000,
    "numberOfRebuyAllowed" : 1,
    "hourLimitForRebuy" : 1,
    "rebuyHourFactor" : 1,
    "gameInfo" : "Testing 1",
    "gameInterval" : 1,
    "blindMissed" : 2,
    "channelVariation" : "Texas Hold’em",
    "rakeRule" : "5791f3c3e7b566a92ac046b7",
    "isActive" : true,
    "channelType" : "NORMAL",
    "totalGame" : 0,
    "totalPot" : 0,
    "avgPot" : 0,
    "totalPlayer" : 0,
    "totalFlopPlayer" : 0,
    "avgFlopPercent" : 0,
    "totalStack" : 0
},{
    "isRealMoney" : false,
    "channelName" : "Manila Gamer omaha",
    "turnTime" : 20,
    "isPotLimit" : true,
    "maxPlayers" : 9,
    "minPlayers" : 2,
    "smallBlind" : 20,
    "bigBlind" : 40,
    "isStraddleEnable" : false,
    "minBuyIn" : 500,
    "maxBuyIn" : 2000,
    "numberOfRebuyAllowed" : 1,
    "hourLimitForRebuy" : 1,
    "rebuyHourFactor" : 1,
    "gameInfo" : "Testing 1",
    "gameInterval" : 1,
    "blindMissed" : 2,
    "channelVariation" : "Omaha",
    "rakeRule" : "5791f3c3e7b566a92ac046b7",
    "isActive" : true,
    "channelType" : "NORMAL",
    "totalGame" : 0,
    "totalPot" : 0,
    "avgPot" : 0,
    "totalPlayer" : 0,
    "totalFlopPlayer" : 0,
    "avgFlopPercent" : 0,
    "totalStack" : 0
},{
    "isRealMoney" : true,
    "channelName" : "Agra Heights texas",
    "turnTime" : 20,
    "isPotLimit" : false,
    "maxPlayers" : 6,
    "minPlayers" : 2,
    "smallBlind" : 100,
    "bigBlind" : 200,
    "isStraddleEnable" : false,
    "minBuyIn" : 1000,
    "maxBuyIn" : 5000,
    "numberOfRebuyAllowed" : 1,
    "hourLimitForRebuy" : 1,
    "rebuyHourFactor" : 1,
    "gameInfo" : "abc",
    "gameInterval" : 1,
    "blindMissed" : 2,
    "channelVariation" : "Texas Hold’em",
    "rakeRule" : "5791f3c3e7b566a92ac046b7",
    "isActive" : true,
    "channelType" : "NORMAL",
    "totalGame" : 0,
    "totalPot" : 0,
    "avgPot" : 0,
    "totalPlayer" : 0,
    "totalFlopPlayer" : 0,
    "avgFlopPercent" : 0,
    "totalStack" : 0
}];

module.exports = newTables;